#!/usr/bin/env pwsh
# Central ERP Hub - Quick Start Script (Windows PowerShell)

$ErrorActionPreference = "Stop"

Write-Host "🏢 Central ERP Hub - Quick Start" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan
Write-Host ""

# Check Python
Write-Host "Checking Python installation..." -ForegroundColor Yellow
try {
    $pythonVersion = python --version 2>&1
    Write-Host "✓ Python found: $pythonVersion" -ForegroundColor Green
} catch {
    Write-Host "✗ Python not found. Please install Python 3.11+" -ForegroundColor Red
    exit 1
}

# Check/Create virtual environment
if (-not (Test-Path ".venv")) {
    Write-Host "Creating virtual environment..." -ForegroundColor Yellow
    python -m venv .venv
    Write-Host "✓ Virtual environment created" -ForegroundColor Green
} else {
    Write-Host "✓ Virtual environment exists" -ForegroundColor Green
}

# Activate virtual environment
Write-Host "Activating virtual environment..." -ForegroundColor Yellow
& ".\.venv\Scripts\Activate.ps1"
Write-Host "✓ Virtual environment activated" -ForegroundColor Green

# Install dependencies
Write-Host "Installing dependencies..." -ForegroundColor Yellow
pip install -q --upgrade pip
pip install -q -r requirements.txt
Write-Host "✓ Dependencies installed" -ForegroundColor Green

# Check for .env file
if (-not (Test-Path ".env")) {
    Write-Host "⚠ No .env file found" -ForegroundColor Yellow
    Write-Host "Generating BLOB_KEY..." -ForegroundColor Yellow
    $blobKey = python -c "import secrets; print(secrets.token_hex(32))"
    
    Write-Host "Creating .env file..." -ForegroundColor Yellow
    @"
# Generated by quick-start.ps1
BLOB_KEY=$blobKey
ADMIN_TOKEN=dev_admin_token
ADMIN_JWT_SECRET=dev_jwt_secret
LOG_LEVEL=INFO
ENABLE_BLOB_STREAMING=true
"@ | Out-File -FilePath ".env" -Encoding UTF8
    
    Write-Host "✓ .env file created with generated BLOB_KEY" -ForegroundColor Green
} else {
    Write-Host "✓ .env file exists" -ForegroundColor Green
}

# Load environment variables
Write-Host "Loading environment variables..." -ForegroundColor Yellow
Get-Content .env | ForEach-Object {
    if ($_ -match '^([^#][^=]+)=(.*)$') {
        $key = $matches[1].Trim()
        $value = $matches[2].Trim()
        [Environment]::SetEnvironmentVariable($key, $value, "Process")
    }
}
$env:PYTHONPATH = "."
Write-Host "✓ Environment configured" -ForegroundColor Green

# Run smoke tests
Write-Host ""
Write-Host "Running smoke tests..." -ForegroundColor Yellow
try {
    python dev\scripts\smoke_test.py
    Write-Host "✓ Smoke tests passed" -ForegroundColor Green
} catch {
    Write-Host "⚠ Smoke tests failed (server may not be running yet)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=================================" -ForegroundColor Cyan
Write-Host "✓ Setup Complete!" -ForegroundColor Green
Write-Host "=================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Start the server:" -ForegroundColor White
Write-Host "     uvicorn hub.main:app --host 127.0.0.1 --port 8000 --reload" -ForegroundColor Gray
Write-Host ""
Write-Host "  2. Start frontend (in another terminal):" -ForegroundColor White
Write-Host "     python -m http.server 8080 --directory dev/frontend" -ForegroundColor Gray
Write-Host ""
Write-Host "  3. Open your browser:" -ForegroundColor White
Write-Host "     Dashboard: http://127.0.0.1:8080/index.html" -ForegroundColor Gray
Write-Host "     API Docs:  http://127.0.0.1:8000/docs" -ForegroundColor Gray
Write-Host ""
Write-Host "Press any key to start the server now, or Ctrl+C to exit..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

Write-Host ""
Write-Host "Starting Central ERP Hub server..." -ForegroundColor Cyan
uvicorn hub.main:app --host 127.0.0.1 --port 8000 --reload
